### ISSUE TITLE
panic on struct assignment

### ISSUE THREAD

**Issue by jrmuizel** [jyn514/rcc#100] opened 2019-10-17 00:35 UTC
The following code:
```c
struct Foo {
        int x;
};

int main() {
        struct Foo f;
        struct Foo g;
        f.x = 4;
        g = f;
        return 5;
}
```

crashes with:
```
thread 'main' panicked at 'INVALID encountered', /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/ir/types.rs:327:28
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: <cranelift_codegen::ir::types::Type as core::fmt::Display>::fmt
   8: core::fmt::write
   9: alloc::fmt::format
  10: cranelift_codegen::verifier::Verifier::typecheck
  11: cranelift_codegen::verifier::Verifier::run
  12: cranelift_codegen::verifier::verify_function
  13: rcc::ir::Compiler::compile_func
  14: rcc::ir::compile
  15: rcc::compile
  16: rcc::real_main
  17: rcc::main
  18: std::rt::lang_start::{{closure}}
  19: std::panicking::try::do_call
  20: __rust_maybe_catch_panic
  21: std::rt::lang_start_internal
  22: std::rt::lang_start
  23: main
```

**Comment by jyn514** [comment] 2019-10-17 01:21
Thank you for contributing! This is closely related to https://github.com/jyn514/rcc/issues/71 and has the same root cause: the parser needs to desugar struct assignment into multiple operations. Closing as a duplicate, but if you run into any more bugs I'd love to hear about them.

**Closed** 2019-10-17 01:21 UTC
Labels: bug, duplicate, parser, structs

**Comment by jyn514** [comment] 2019-10-26 02:29
I added a better error message for this in 44c058700b14a5a0b3eae1f6a4bd88764c113b10 :)

**Comment by jyn514** [comment] 2019-12-07 05:49
@jrmuizel I fixed this a few days ago, see https://github.com/jyn514/rcc/issues/120 :)
